### ISSUE TITLE
wordpress error when we try to view image links from the data download

### ISSUE THREAD

**Issue by stephtngu** [consumer-reports-digital-lab/dark-patterns#100]
![image](https://user-images.githubusercontent.com/60265274/119748161-45ad7480-be62-11eb-9967-71401b57d762.png)

**Comment by tbeck** [comment]
Hi @stephtngu - Looking into this now to see if there is anything we can do and filing a ticket with the WP hosting provider Kinsta

**Comment by tbeck** [comment]
![image](https://user-images.githubusercontent.com/242469/119751217-99fb2900-be4f-11eb-98fb-2103e9016207.png)

Kinsta resolved the issue and the WP admin is now available.

**Comment by stephtngu** [comment]
thanks!
