### ISSUE TITLE
sightings page is down

### ISSUE THREAD

**Issue by stephtngu** [consumer-reports-digital-lab/dark-patterns#101]
![image](https://user-images.githubusercontent.com/60265274/119748237-7392b900-be62-11eb-82e1-5d31f324511a.png)

**Comment by tbeck** [comment]
Hi @stephtngu - This looks like it is stemming from an error on the Kinsta (WP) server.
https://darkpatterns.kinsta.cloud/wp-admin/

We will dig in further to see if there is anything we can do, otherwise filing a support ticket now with Kinsta.

**Comment by tbeck** [comment]
Kinsta resolved the root issue and I have triggered a rebuild in Gatsby. This should resolve this issue.

**Comment by tbeck** [comment]
@stephtngu - Just confirming that the sightings page is resolving as expected now. We have added logic to help account for instances where the WP server is "unavailable" as well. #101

**Comment by stephtngu** [comment]
thanks!
