### ISSUE TITLE
Dark patterns are being published that are not on the published list

### ISSUE THREAD

**Issue by stephtngu** [consumer-reports-digital-lab/dark-patterns#103]
Here are the listed dark patterns that are published on WP: 
https://darkpatterns.kinsta.cloud/wp-admin/edit.php?post_status=publish&post_type=example

We are seeing some of the dark patterns that I changed the Title to: Not a dark pattern, Unverified, etc. (BUT DID NOT PUBLISH) show up in the feed in the website. 

Any idea why this may be happening?
![image](https://user-images.githubusercontent.com/60265274/120495773-006dd300-c38b-11eb-9651-6068f1cb04b4.png)

**Comment by stephtngu** [comment]
For the examples above, I changed the titles to "unvalidated screenshot" and "not a dark pattern" but did not publish, and they seem to be pushing to publish live with the changed titles.

**Comment by stephtngu** [comment]
and when you click on the error cards it shows this: 

![image](https://user-images.githubusercontent.com/60265274/120496415-8be76400-c38b-11eb-8077-6be911f64b3d.png)

**Comment by tbeck** [comment]
@stephtngu - Looking into this now. We are not getting the issue locally. I may try triggering a rebuild in Gatsby Cloud, but want to see if I can replicate the issue first.

**Comment by stephtngu** [comment]
I'll list the 4 I'm seeing in case helpful to find the problematic ones: 
![image](https://user-images.githubusercontent.com/60265274/120496942-fef0da80-c38b-11eb-9649-1d0c69b41251.png)
![image](https://user-images.githubusercontent.com/60265274/120496958-03b58e80-c38c-11eb-8a5f-b3784ceeeb87.png)
![image](https://user-images.githubusercontent.com/60265274/120496978-087a4280-c38c-11eb-8450-c0319063a3b0.png)
![image](https://user-images.githubusercontent.com/60265274/120497010-0dd78d00-c38c-11eb-9210-938717e15e5f.png)

**Comment by tbeck** [comment]
Thanks @stephtngu - I pushed a change #104 that adds a redundant filter for that page. The build was successful and it looks like the issue is fixed. I think that we should continue to monitor the sightings page though.

**Comment by stephtngu** [comment]
Nice! What was the cause - so I can perhaps be aware/avoid replicating? Me changing the titles (without publishing) triggered something?

**Comment by tbeck** [comment]
I'm not sure... I don't think that it was anything that you did within the CMS.  I am researching the gatsby-source-wordpress documentation to see if I can find other possible causes and will probably submit a support ticket with Gatsby Cloud to see if they can provide any insight.  It's my understanding that draft content should not be included by default and the filter that we added is redundant.

I'll let you know if I find a clear explanation of the cause though.

**Comment by stephtngu** [comment]
sounds good, will close for now.
