### ISSUE TITLE
Submissions don't seem to be working - page gets stuck on "loading" 

### ISSUE THREAD

**Issue by stephtngu** [consumer-reports-digital-lab/dark-patterns#107]
![image](https://user-images.githubusercontent.com/79227044/123469408-00937400-d5c1-11eb-9848-3a839c09726f.png)

**Comment by tbeck** [comment]
Looking into this... I'm able to get the form to load, however on submission I get a 403 error. This is a server side error that post request is not authenticated.

We will continue to dig in to see if we can figure out the reason.  Has anything been changed recently on WP side?

**Comment by tbeck** [comment]
@stephtngu - It appears that the token had expired and was causing the auth error on submissions.

We have fixed and pushed... everything should be working as expected now.

**Comment by stephtngu** [comment]
@tbeck thank you! This is resolved. 

![image](https://user-images.githubusercontent.com/60265274/123478827-03489600-d5ce-11eb-9e28-9b39c691f88e.png)
