### ISSUE TITLE
Need to change CR logo in footer to “incubated by CR Digital Lab” 

### ISSUE THREAD

**Issue by stephtngu** [consumer-reports-digital-lab/dark-patterns#13]
Ben will provide logofile

![image](https://user-images.githubusercontent.com/60265274/117222612-da7bff80-add9-11eb-8d3a-e5924cd0fd72.png)

**Comment by stephtngu** [comment]
+ @benrito for awareness.

**Comment by stephtngu** [comment]
@benrito to clarify this ask, do you want just this logo above to replace the current CR logo in the footer? you initially mentioned you wanted it to say "incubated by"  so did you want to add that text?

**Comment by benrito** [comment]
Hey @nathanielfostan @stephtngu — 

Just had a convo about this— in the end, we can probably skip the logo entirely and just have text that says:

An experiment incubated by the [CR Digital Lab](http://lab.cr.org)

**Comment by stephtngu** [comment]
![image](https://user-images.githubusercontent.com/60265274/118065951-d4eb6000-b36b-11eb-93a5-996be3a4fe1f.png)
This looks good to me @benrito did you need it to link to the digital lab? if yes, that's the only remaining fix i see for this one. 

cc @nathanielfostanperry
