### ISSUE TITLE
Added "Partner" + Logo to WP & doesn't show up in staging site

### ISSUE THREAD

**Issue by stephtngu** [consumer-reports-digital-lab/dark-patterns#14]
Here is what I submitted: 
![image](https://user-images.githubusercontent.com/60265274/117222701-13b46f80-adda-11eb-984c-0ebde2e43326.png)
![image](https://user-images.githubusercontent.com/60265274/117222713-1b741400-adda-11eb-86c8-6e69de6236b8.png)

Here is what is showing on the website: 
![image](https://user-images.githubusercontent.com/60265274/117222664-fe3f4580-add9-11eb-90c0-6a75d2ffac14.png)

**Comment by nathanielfostanperry** [comment]
@stephtngu can you confirm this is behaving as expected?

**Comment by stephtngu** [comment]
this works thank you. @nathanielfostanperry do you know how we can control the order of these logos? I tried changing the timestamp of the image upload which doesn't seem to work.

**Comment by stephtngu** [comment]
This issue seems to be reappearing?


![image](https://user-images.githubusercontent.com/60265274/118067967-8b047900-b36f-11eb-908c-bf2f8fd33355.png)



![image](https://user-images.githubusercontent.com/60265274/118067983-9192f080-b36f-11eb-8d2b-b96d6592a4de.png)

**Comment by stephtngu** [comment]
@tbeck it shows up now which is good, but when i reorder the time stamps on the images to reorder the logos, it does not change.

**Comment by stephtngu** [comment]
done!
