### ISSUE TITLE
No source link currently included in the dark pattern specific page

### ISSUE THREAD

**Issue by stephtngu** [consumer-reports-digital-lab/dark-patterns#28]
Currently, we ask for a source link in the form, but that source is not included in the dark pattern specific page. In order to correctly "cite" the source, could we include this please? 

![image](https://user-images.githubusercontent.com/79227044/117600996-1afdb500-b11b-11eb-99b2-b9e50143f858.png)

![image](https://user-images.githubusercontent.com/79227044/117600812-b3476a00-b11a-11eb-9725-5204e295e8f6.png)

**Comment by snguyen-gov** [comment]
linking this with #18

**Comment by nathanielfostanperry** [comment]
@stephtngu That makes sense for probably most of the cases that will be received. If we don't have a URL though, should we pitch to just hide that section? 

We have examples that currently don't link any where such as [this MS Edge case](https://darkpatterns.gatsbyjs.io/example/persuaded-me-to-use-the-browser-with-button-colors/) "From setting up a PC"

**Comment by stephtngu** [comment]
@nathanielfostanperry yes agreed - if no source is included (meaning no legitimate text or URL in that box at all), then we should hide that section.

**Comment by tbeck** [comment]
@stephtngu - We have updated to add logic for the hyperlink versus string. It requires that all hyperlinks start with the protocol (http or https)

**Comment by nathanielfostanperry** [comment]
@stephtngu Added logic so if a URL is entered in the form it will [display a link like this ](https://gyazo.com/12aa581a6b1af32d3d36e5fa6e3c1c28)
otherwise we just get a [text string like this](https://gyazo.com/7d675b8a8a6d858d340aed495c0ff901)

**Comment by stephtngu** [comment]
@nathanielfostanperry Thanks! did you use the text "View Dark Pattern" to obscure the lengthy URL or make it cleaner or something else? Curious what your thinking was behind this.

**Comment by benrito** [comment]
Sorry for coming in late. Steph, don't think we want to expose this... if the patterns get fixed we'll be linking to sites where the pattern may no longer be there. 

Think this is an instance where collecting the structured data is good, but surfacing it is bad.

Isn't it better to have that data stored in the CMS and included in the description, per the curators' discretion?

Thoughts?

**Comment by stephtngu** [comment]
@benrito - I believe @nathanielfostanperry designed this so that the curator can take out the source completely for whatever reason (including but not limited to if the pattern may no longer be there). If the source / text / link is NOT present, then that section will not show up. 

The reason to keep this here as an option is the use case where people may WANT to know where the dark pattern came from (assuming it still exists), especially if they did not experience it DIRECTLY themselves but are citing someone's tweet, post, image, etc. If someone asks for the source, wouldn't it be helpful to point them to that source?

**Comment by benrito** [comment]
If we're willing to remove the text if the link no longer applies, that can work.
