### ISSUE TITLE
Add footer links to "How we'll use your data" and "User agreement"

### ISSUE THREAD

**Issue by stephtngu** [consumer-reports-digital-lab/dark-patterns#42]
How we'll use your data: [Pending the creation of a page for this] see text in content repo.
User agreement: https://www.consumerreports.org/cro/2015/01/user-agreement/index.htm

**Comment by benrito** [comment]
@nathanielfostanperry , sorry for the late notice on this — can we change the footer to "How We'll Use Your Submission" (instead of "Data")

**Comment by nathanielfostanperry** [comment]
@benrito Footer links have been updated. 

I opened a separate issue #62 to add in the content when it is finalized. Looks like there is still some discussion in the content doc.

**Comment by benrito** [comment]
Looks good!
