### ISSUE TITLE
In place of everywhere there is <p class="text-small">  can we standardize so that the smallest text size is the text size under normal <p>?

### ISSUE THREAD

**Issue by stephtngu** [consumer-reports-digital-lab/dark-patterns#49]
For example - can we please use the text size under "our purpose" as the smallest text across the site? 

Places where small text appears: 

![image](https://user-images.githubusercontent.com/60265274/117877211-4646e800-b272-11eb-84d1-598b82fd4ff8.png)

![image](https://user-images.githubusercontent.com/60265274/117878691-fff28880-b273-11eb-96da-812429c6dfc7.png)

![image](https://user-images.githubusercontent.com/60265274/117879430-fc133600-b274-11eb-871a-98eb43a3f66c.png)

![image](https://user-images.githubusercontent.com/60265274/117879484-0c2b1580-b275-11eb-8ddc-b0dff920fcca.png)

**Comment by nathanielfostanperry** [comment]
This will probably need some additional design input to reenforce hierarchy

**Comment by nathanielfostanperry** [comment]
@stephtngu Updated text size and hierarchy

**Comment by stephtngu** [comment]
looks great!
