### ISSUE TITLE
"Our purpose" text in home page footer adjustment

### ISSUE THREAD

**Issue by benrito** [consumer-reports-digital-lab/dark-patterns#51]
Replacing the text in "Our Purpose"

The Dark Patterns Tip Line is a platform people can use to submit deceptive designs they encounter in everyday digital products and services. Through crowdsourcing human stories of digital manipulation and amplifying people’s voices, we will raise awareness of the real-life harms that result from deceptive design.

The submissions reflect the views of the people who submitted them, and not necessarily those of Consumer Reports. They have not been checked by Consumer Reports for accuracy.

**Comment by nathanielfostanperry** [comment]
@benrito this has been updated on the site

**Comment by benrito** [comment]
Looks good!
