### ISSUE TITLE
Social share image?

### ISSUE THREAD

**Issue by benrito** [consumer-reports-digital-lab/dark-patterns#53]

**Comment by stephtngu** [comment]
I'm not actually sure how to check if this has been implemented yet. Where should I be looking @tbeck ?

**Comment by tbeck** [comment]
@nathanielfostanperry 
Thanks for adding the temp social share image. Can you update the [image](https://github.com/consumer-reports-digital-lab/dark-patterns/blob/main/static/img/lib-share.png) to be 1200 x 628?

**Comment by tbeck** [comment]
@stephtngu - Here is an online meta tag check: https://www.heymeta.com/url/darkpatternstipline.org

Let me know if we need to adjust any copy?

**Comment by stephtngu** [comment]
![image](https://user-images.githubusercontent.com/60265274/118837665-0e076100-b893-11eb-8917-8f3d0eeb1a2a.png)
cc: @tbeck @nickkrusick seems to be an issue with twitter share

**Comment by tbeck** [comment]
<img width="1010" alt="Screen Shot 2021-05-19 at 8 37 04 AM" src="https://user-images.githubusercontent.com/242469/118841749-6cc1e000-b87d-11eb-8545-c8dc85444b85.png">

@stephtngu - we updated the share image include an abosolute path and tested to confirm the fix.

**Comment by stephtngu** [comment]
![image](https://user-images.githubusercontent.com/60265274/118841944-c2ef4d00-b896-11eb-90c5-7c8f85feecdf.png)

@tbeck i'm still getting this in twitter - but i also see the validator update. any reason why this may be?

**Comment by tbeck** [comment]
@stephtngu - There may be some type of caching mechanism on Twitter’s end where the preview doesn’t show up right away?

@nick got the same thing but the social share image was present in the actual tweet.
Preview: https://gyazo.com/04440fa9fd26857e954ea8892f4e8f85

Tweet: https://gyazo.com/22ac95d2aef6e518238b194acff9d854

**Comment by tbeck** [comment]
Anytime! Let us know if you continue to have issues and we will continue to monitor on this end to see if the preview resolves.

**Comment by stephtngu** [comment]
yes thank you!
