### ISSUE TITLE
include images for "dark patterns are everywhere" carousel on home page for different industries

### ISSUE THREAD

**Issue by stephtngu** [consumer-reports-digital-lab/dark-patterns#54]
this seems to be being built out as we speak, but wanted to flag the images for each of the industries that are not complete just yet. 

![image](https://user-images.githubusercontent.com/60265274/117911403-b6259480-b2ab-11eb-9bc2-a3a2ec57ddf9.png)

**Comment by nathanielfostanperry** [comment]
@stephtngu This is up for review
