### ISSUE TITLE
Change email field to explicitly say optional: "Email (Optional)"

### ISSUE THREAD

**Issue by stephtngu** [consumer-reports-digital-lab/dark-patterns#55]
@benrito - based on email thread and issues with AN / do you agree with these changes? 

- [x] Change email field to say "Email (Optional)"
- [x] Change "Stay informed..." to "For us to reach out if we have questions only"

![image](https://user-images.githubusercontent.com/60265274/117913333-313c7a00-b2af-11eb-8691-2bc3700bf1fa.png)

**Comment by benrito** [comment]
I'll close #50 which is redundant.

Steph, how about "You can reach me at..."

**Comment by stephtngu** [comment]
@benrito hmm perhaps "For outreach in case we have questions" or something is more representative of the purpose of the email collection to begin with

**Comment by nathanielfostanperry** [comment]
@benrito @stephtngu This is up for review

**Comment by benrito** [comment]
Looks good. Note the tooltip should end at "we won't share your email"
