### ISSUE TITLE
page meta defaults and management through the CMS 

### ISSUE THREAD

**Issue by tbeck** [consumer-reports-digital-lab/dark-patterns#59]
@benrito - 
Here are the fields that we are currently accounting for and their default values. Let me know if you think we need to make adjustments. These values get used for page meta including OpenGraph and Twitter specific meta tags. We also have set it up so that meta can be overwritten on a page by page basis in WP (Through the Yoast Plugin)

{
  "title": "Dark Patterns Tipline",
  "description": "Need copy...",
  "url": "https://____.com", // Site domain?
  "inLanguage": "en-US", // Language Tag on <html> element
  "logo": "/img/logo.png", // Used for SEO and favicon
  "ogLanguage": "en_US", // Facebook Language
  "shareImage": "/img/lib-share.png" // Default social share image
  "twitter": "" // Need?
  "facebook": "" // Need?
}

1. Should we account for a title pattern? ie... <page.title> | Dark Pattern Tipline
2. What will the domain end up being?
3. Ocupop will create share images and favicons and push these up as soon as possible for testing.

**Comment by benrito** [comment]
Hey crew,

"title": "Dark Patterns Tipline",
"description": "The Dark Patterns Tip Line is a platform people can use to submit deceptive designs they encounter in everyday digital products and services.",
"url": "https://darkpatternstipline.org", // Site domain?
"inLanguage": "en-US", // Language Tag on element
"logo": "/img/logo.png", // Used for SEO and favicon
"ogLanguage": "en_US", // Facebook Language
"shareImage": "/img/lib-share.png" // Default social share image

N/A:

"twitter": "" // Need?
"facebook": "" // Need?

**Comment by tbeck** [comment]
Thanks @benrito
