### ISSUE TITLE
added new test team member, does not appear in gatsby site

### ISSUE THREAD

**Issue by stephtngu** [consumer-reports-digital-lab/dark-patterns#67]
![image](https://user-images.githubusercontent.com/60265274/118068419-593fe200-b370-11eb-8b1e-06c32ed911b7.png)

![image](https://user-images.githubusercontent.com/60265274/118068482-6d83df00-b370-11eb-8ff2-1a12f8fd6c00.png)

**Comment by tbeck** [comment]
@stephtngu - It looks like this is resolved now that the build is succesful: https://darkpatterns.gatsbyjs.io/about#team

**Comment by stephtngu** [comment]
I deleted the team member "Test person" but it still is there: 

![image](https://user-images.githubusercontent.com/60265274/118225290-d9d70f00-b452-11eb-9f7a-5cd43477b74a.png)

**Comment by stephtngu** [comment]
fixed!
