### ISSUE TITLE
add feedback mechanism (contact or email)

### ISSUE THREAD

**Issue by stephtngu** [consumer-reports-digital-lab/dark-patterns#73]
Hey guys - I know this is last minute. Talked to @benrito. 

we need a way for people to reach out. there is no way for anyone to get in touch (complain, make a suggestion, journalist outreach, be a partner). 

is there way to add a [contact / feedback] link and have it go somewhere where people can submit comments? 
* can be stored in wordpress
* can be forwarded to me 

Can be simple - we need some / any mechanism to do this. 

OR we can do an email: hi@darkpatternstipline.org  and stick in footer. 

thoughts? @tbeck

**Comment by stephtngu** [comment]
@benrito leaning toward a hi@darkpatternstipline.org email being the simplest option (as opposed to creating another form somewhere on the website), but would need to set up an email.

**Comment by tbeck** [comment]
@stephtngu - Let us know where this lands... we can add another form that posts to WP if needed. Otherwise, I agree... the email is the easiest fix.

**Comment by benrito** [comment]
Hey all,

Been working through this morning. Getting the email setup might take
longer than we've got, because I've got to coordinate with IT here. I
wonder if we can implement a form that sends to an email address, and swap
the email address in later.

Alternately, we can use a mailto: link for ***@***.*** for
the time being.

Thoughts?

-Ben

**Comment by stephtngu** [comment]
@benrito this is slightly unclear. what do you mean by: "Alternately, we can use a mailto: link for ***@***.*** ? 

and what specifically is needed for email setup that requires IT coordination? We can have it sent to my email, unless you're suggesting otherwise. what do you mean?

**Comment by stephtngu** [comment]
@benrito @tbeck 

What we decided in the call: 
* Add a form page for "contact us"
* Text: We’re here to help and answer any questions you might have about submitting to or supporting The Dark Patterns Tip Line. We won't share your email
* Email address _[form field]_
* Message _[form field]_
* The messages will be added into WP in some link SN can access to address.

**Comment by tbeck** [comment]
This should be ready to test: https://darkpatternstipline.org/contact

**Comment by stephtngu** [comment]
i'm unable to test this due to error: 
![image](https://user-images.githubusercontent.com/60265274/118708160-62560680-b7e9-11eb-941d-e9ccd0162fa2.png)

also using the gatsby site, i sent 2 messages but did not see the notification via email - is it no longer sending a note . is this because i'm using gatsby and not the real site (https://darkpatternstipline.org/contact)?

**Comment by stephtngu** [comment]
i used incognito and was able to enter the site (do you know why this may be)?

upon submitting a message, there is no email notification. i went to WP under "feedback messages" (unsure if this is where the messages would be but guessed), and didn't find anything there. let me know what i'm missing / how i may be doing this incorrectly @tbeck ! thank you for your help.

![image](https://user-images.githubusercontent.com/60265274/118708818-325b3300-b7ea-11eb-8eac-ae270e2955b3.png)

**Comment by tbeck** [comment]
@stephtngu - We updated the env variables because the authentication token was not valid after we made the switch to the new URL. That should work now and you should receive notifications for all submissions.
