### ISSUE TITLE
Add Matomo plugin

### ISSUE THREAD

**Issue by benrito** [consumer-reports-digital-lab/dark-patterns#76]
Hey fellas, we may be able to do ourselves with admin privs but dropping here ahead of Weds: https://matomo.org/installing-matomo-for-wordpress/

**Comment by tbeck** [comment]
@benrito - We were able to get the Matomo analytics to track visitors to the site and have disabled cookies in the configuration.

Here is a link to the analytics dashboard in WP to review: [[Dashboard](https://darkpatterns.kinsta.cloud/wp-content/plugins/matomo/app/index.php?idSite=1&period=day&date=yesterday&module=CoreHome&action=index#?idSite=1&period=day&date=2021-05-18&segment=&category=Dashboard_Dashboard&subcategory=1)]

Let me know if we need to adjust any configuration options as they may need to be changed on the Gatsby side.

**Comment by benrito** [comment]
Hot damn, that is impressive! I checked things out on the client side and everything looks clean.

I won't be able to peer into the dashboard in time, so re-assigning to @stephtngu. Looks OK to you?

**Comment by stephtngu** [comment]
i won't be able to test this in depth by tomorrow and have never used it before but it looks as if we've got 35 visitors which is what we were looking for. feel free to close as appropriate @benrito

**Comment by benrito** [comment]
Awesome, thanks Ocupop team!
