### ISSUE TITLE
Fix call-to Google Font from stylesheet 

### ISSUE THREAD

**Issue by stephtngu** [consumer-reports-digital-lab/dark-patterns#79]
from our convo cc: @benrito @tbeck

**Comment by tbeck** [comment]
@benrito - We found that the Google Font API call was coming from a checkbox component. We are refactoring to remove and will comment here when it is ready to test.

**Comment by tbeck** [comment]
@benrito / @stephtngu - All calls to Google Fonts API have been removed and this is ready to test/review.
