### ISSUE TITLE
Add text edits on form *AND* add text after form is submitted. 

### ISSUE THREAD

**Issue by stephtngu** [consumer-reports-digital-lab/dark-patterns#92]
Hi all. We got some feedback from a federal regulator today and need your help to see if we can make some quick text updates in 2 places: 
1. on the top of the form
2. in the text after you submit a pattern and it says "successful submission thank you, etc"

We are still getting legal approval so do not make any updates yet, but wanted to highlight this as a heads up. I'll let you know once we get approval from legal to post. after that, it'd be great to get your guidance on how to make text changes asap.

cc: @benrito 

See text in question here for context: 
https://docs.google.com/document/d/1KbVO5ZBlMXRRle0HFpzP7rQMuRWpDeSqoAVSF0V5KT0/edit

**Comment by tbeck** [comment]
Hi @stephtngu - We are happy to make this update as soon as it is ready. As an alternative you can also edit this copy directly in Github here: https://github.com/consumer-reports-digital-lab/dark-patterns/blob/main/src/components/examples/PostExample.jsx

Keep us posted as the conversation progresses.

**Comment by stephtngu** [comment]
Yes! Approved. I am in transit and can’t get to a computer / gh until later this eve. If you have time i would be greatly appreciative if you could help with changes . And if not I will get to it later.

**Comment by tbeck** [comment]
@stephtngu - No problem... These changes have been merged as part of #94 

https://darkpatternstipline.org/report/

**Comment by stephtngu** [comment]
thanks @tbeck ! - keeping this open as there seems to be a change or two more that i make copy edits to the github link above.
