### ISSUE TITLE
a way to better view / curate the data? e.g.) change column widths?

### ISSUE THREAD

**Issue by stephtngu** [consumer-reports-digital-lab/dark-patterns#96]
day 1 and we have over 200 submissions 🎉 

just brainstorming with you all before we dive into curation - @tbeck @nathanielfostanperry, is there a fairly low-effort way to get a simpler way to view all of the submissions? even if we adjusted the column widths (especially "description") so the post wasn't so narrow, it could be easier to go through. 

![image](https://user-images.githubusercontent.com/60265274/119034420-4898f880-b97c-11eb-817c-4ac34aad278d.png)

**Comment by stephtngu** [comment]
Your screenshot looks much better than mine - any ideas why this may be happening? My width is still pretty small. 


![image](https://user-images.githubusercontent.com/60265274/119211376-baa63600-ba7f-11eb-81b6-fc8348cbec18.png)

**Comment by tbeck** [comment]
@stephtngu - Maybe if you change your "screen options" and limit the visible columns. ie... categories and industries.  This should buy you some screen real estate.  These settings only apply to your individual viewpoint.

**Comment by stephtngu** [comment]
@tbeck Tried to copy your instructions above, but column still seems to be fairly limited. Is there any way we can permanently widen the column for description and make the ones with fairly small text (e.g. image size, affiliated company, sourcelink, etc.)? 

![image](https://user-images.githubusercontent.com/60265274/119412667-41465780-bcba-11eb-8f4c-d5956b58cfd0.png)

**Comment by tbeck** [comment]
Hi @stephtngu - Sorry to hear that didn't help.
I'll look into other ways to customize the viewpoint. What are the priority columns that you need for this viewpoint to be useful?

**Comment by stephtngu** [comment]
deprioritizing this
